version: "3.8"

services:
  expense-app:
    build: .
    container_name: expense-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:diOjgnDgxtZNDqSgiPqbDVEPbnospkFz@thomas.proxy.rlwy.net:58163/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: YOUR_PASSWORDdiOjgnDgxtZNDqSgiPqbDVEPbnospkFz
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      MAIL_USERNAME: mohapatraarun64@gmail.com
      MAIL_PASSWORD: cepkxxmmzxzrujzg

      RAZORPAY_KEY: rzp_test_SWgcF87G8agcf8
      RAZORPAY_SECRET: nvm2b8J7zUbKrXvLDA9pH3cf
    restart: always